export const AreaItem = [
    {name: "博多", code: "Y700"},
    {name: "中洲・中洲川端", code: "Y705"},
    {name: "天神・西中洲・春吉", code: "Y706"},
    {name: "西新・姪浜・その他西エリア", code: "Y710"},
    {name: "吉塚・香椎・その他東エリア", code: "Y711"},
    {name: "大名・今泉・警固", code: "Y712"},
    {name: "薬院・平尾・高砂", code: "Y713"},
    {name: "大橋・その他南地区", code: "Y714"},
    {name: "北九州（小倉・門司）", code: "Y730"},
    {name: "北九州（八幡・黒崎・折尾）", code: "Y731"},
    {name: "飯塚・筑紫野", code: "Y732"},
    {name: "久留米", code: "Y900"},
    {name: "福岡県その他", code: "Y901"},
]